### ISSUE TITLE
How to use RapidCFD - differences to openFOAM

### ISSUE THREAD

**Issue by Flowier** [Atizar/RapidCFD-dev#86] opened 2021-06-19 12:22 UTC
Hello together :) 

i tried to solve openFOAM tutorials with RapidCFD, but actually nothing worked out. 

Is there some sort of documentation? I want to learn how to use the rapid solvers properly.

Best wishes
Ingo

**Comment by TonkomoLLC** [comment] 2021-06-19 13:42
Dear Ingo,

There is no specific documentation for RapidCFD. The case setup generally follows that of OpenFOAM 2.3.x. Most of the differences between OpenFOAM 2.3.x and RapidCFD will be in `system/fvSchemes` and `system/fvSolution` (because some schemes are not implemented in `RapidCFD`, and the `AINV` preconditioner is not found in OpenFOAM 2.3.x).  

I have placed some test cases [here](https://github.com/TonkomoLLC/RapidCFD-Tests).  Hopefully they are helpful for getting started. 

Best regards,

Eric

**Comment by Flowier** [comment] 2021-07-08 16:23
Thanks for your help on that, i looked at the cases and they were solvable. 

Now when i try to calculate the rhoSimpleFoam example from openfoam 2.3.0 i get the following error: 
![image](https://user-images.githubusercontent.com/84880991/124957444-621ffd80-e019-11eb-85a2-e0ddbfa028a3.png)

Do you know what this might be?

**Comment by Flowier** [comment] 2021-07-08 16:29
as i see there should be the problem that for the residual of the epsilon there is no value but a -nan so this should be the problem right?

**Comment by TonkomoLLC** [comment] 2021-07-08 16:43
Dear Ingo,

I don't have a machine available at this very moment to check on the DebugSwitch setting in OpenFOAM 2.3.x or RapidCFD.

I think in controlDict you should have a section at the bottom of the file:

```
DebugSwitches
{
    SolverPerformance 2;
}
```

The error you reported might be due to the dictionary entry in controlDict. But I think it is more likely due to the problem with the solution for epsilon, as you reported in the follow-up comment above. 

Thus, my recommendation is to quickly check your controlDict and if that is correct, then the error is probably related to issues with the calculation. What the issue is, I do not know from the information given. 

I wish you good luck with the troubleshooting ahead of you.

Best regards,

Eric

**Comment by Flowier** [comment] 2021-07-10 19:34
That did not work unfortunately. 

Hmm i did not find anything on the internet concerning that error.

**Comment by TonkomoLLC** [comment] 2021-07-10 20:52
Hello,

Sorry, I do not know the answer.  I tried to run the [coil-pisoFoam](https://github.com/TonkomoLLC/RapidCFD-Tests) tutorial with the DebugSwitch enabled. I didn't see any on-screen output but the case didn't crash, either. I strongly urge you to tack back to a known working case and then turn on the debug switch there to ensure the debug switch works. I don't have all the information about your case to know for sure, but based on the screen output I personally think there is something not right with your calculation (due to the -nan residuals) that is causing a problem with the SolverPerformance debug info. What the problem is, I am not sure.

I apologize that I do not know more at this time.  Best of luck with the troubleshooting.

Best regards,

Eric

**Comment by Flowier** [comment] 2021-07-11 10:04
Hey :)

I tried several tutorial cases from the version 2.3.0 and all diverge till i finally get the nan. 

Can you please give me a case for rhoSimpleFoam or rhoPimpleFoam which is working for you? 

Thanks for your help
Ingo

**Comment by Flowier** [comment] 2021-07-11 10:09
Wait a second
I read "Use blockMesh from CPU based OpenFOAM, e.g., 2.3.x, to create the grid."
Does it actually make a difference with which blockMesh i create the grid? I used the of8 all the time

**Comment by Flowier** [comment] 2021-07-11 10:27
and actually the pitzdaily with the rhoPimpleFoam in the Rapidcfd cases given by https://github.com/TonkomoLLC/RapidCFD-Tests is diverging eventually too... 

May this be some issue regarding the compilation of the solvers?

**Comment by TonkomoLLC** [comment] 2021-07-11 15:08
You found the tutorial that I was going to point you to: pitzDaily at [RapidCFD-Tests]( https://github.com/TonkomoLLC/RapidCFD-Tests).  

I just double checked on my laptop and the tutorial works. I am using Ubuntu 20.04 with default gcc and so on, with CUDA v11.1.  I am on the latest commit of RapidCFD as of the time of this post: https://github.com/Atizar/RapidCFD-dev/commit/0fc3af285e3551234ffff9f9402c4c42f088af66 

As to your next question, 

```
Does it actually make a difference with which blockMesh i create the grid? I used the of8 all the time
```

You can use blockMesh from OpenFOAM 8. That is fine. 


As to your specific problem:

```
May this be some issue regarding the compilation of the solvers?
```

There are a lot of details I don't know about your situation. Most of the cases I've helped troubleshoot with compilation errors result in some error being thrown without the first time step even executing. in your case, cases which are known to run successfully in at least my configurations are causing problems on your configuration, even though the solver seems to start and begin executing the solution.

If PiitzDaily doesn't run, does the cavity tutorial run (also found at the same RapidCFD-Tests repo)?  That's about as simple as it gets.  If it does work maybe you can start to troubleshoot the differences between `cavity` and `PitzDaily` in case one library or solver didn't compile correctly?   Or you can just skip to recompiling if that detailed troubleshooting is not worth your time.

Before you recompile, let me just confirm: are you running these cases on 1 GPU or multiple GPU via MPI?  

Should you be running with a multiple GPU configuration via MPI, try running the cases with a single GPU. Does that fix the problem?  If so, we can focus on troubleshooting MPI.

If you are running on a single GPU, then yeah, I would consider a fresh recompile double checking the "arch=sm_xx" settings in the wmake rules directory are appropriate for your GPU (there are several posts in the issues section of the RpaidCFD site on this matter).  I recommend using CUDA 11.1 if possible. Newer versions of CUDA tend to fix older bugs, and anything > 11.1 has not been tested by me or reported by others on CFD-Online or this issue board to work. Thus I cannot vouch for CUDA > version 11.1.

Ok, sorry I don't immediately know the answer to your problem but hope you can get to the bottom of the issue. 

Best regards,

Eric

**Comment by Flowier** [comment] 2021-07-12 15:11
Thanks again for your help!

I ran the cavity case and all worked perfectly fine without any error or diverging solution. 

About my setup: 
I got Ubuntu 16.04 LTS installed with the CUDA 10.1. (I went down to this versions because that was the only installation that worked out for me - with https://github.com/Atizar/RapidCFD-dev/issues/34 The comment from Juradox on 6th April 2018)
I am running all the stuff on 1 GPU: the RTX 3070

**Comment by TonkomoLLC** [comment] 2021-07-12 15:24
Hello,

Thanks for the additional information. I am not sure which item in #34 helped you.   Some new ideas based on your new information:

- Are you using the latest commit of RapidCFD ?  

- Have you set arch=sm_86 in the wmake rules for c and c++ ?  Or if not, what sm number have you set.  [reference](https://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/). 

- I think your GPU is optimized for CUDA >= 11, right?  [Reference](https://docs.nvidia.com/cuda/ampere-compatibility-guide/). What error are you facing when you install and compile with CUDA 11.1?  

There could be something else causing hte problem, but the main item I see right now is that your CUDA version is older than your device. I read online that you should be able to compile with CUDA 10.2 and earlier, but I have anecdotally found that for myself using a CUDA version that is designed for your GPU card is a generally a good idea.

What do you think?

Thanks and best regards,

Eric

**Comment by Flowier** [comment] 2021-07-14 14:33
You are right, probably the sm_.. is the problem here because i did not change it

Now i am encountering the problem that i cannot install drivers that work with CUDA and Ubuntu and i will keep you updated once i compiled with sm_80 or sm_86.

**Comment by TonkomoLLC** [comment] 2021-07-14 14:40
Most of the problems I see these days are related to arch=sm_xx set to the wrong number.

Good luck with your CUDA install and subsequent compilation. Hope it all goes well.

**Comment by Flowier** [comment] 2021-07-18 14:01
Hey @TonkomoLLC :) 

now i finally had time to set up new Ubuntu because the old one could not handle the graphics driver. 

Now i got Ubuntu 20.04 and installed NVIDIA driver 465 and CUDA 11.4. All went good. 

Now i changed the sm number to sm_86 in both files c and c++ in the wmake rules in the RapidCFD-dev folder. 

I got a problem running the compilation: 
When i put the files in ~/RapidCFD/RapidCFD-dev, run "source etc/bashrc" and ":/Allwmake" i get the error:

```
Error: Current directory is not /opt/RapidCFD-dev
Error: Current directory is not $WM_PROJECT_DIR
    The environment variables are inconsistent with the installation.
    Check the OpenFOAM entries in your dot-files and source them.
```

When i then copy the RapidCFD-dev folder to /opt/ , then run "source etc/bashrc" and ":/Allwmake"  again i get the following error: 

```
./Allwmake: 4: wmakeCheckPwd: not found
Error: Current directory is not $WM_PROJECT_DIR
    The environment variables are inconsistent with the installation.
    Check the OpenFOAM entries in your dot-files and source them.
```

So apparently the sourcing does not work if i do a sudo command after it which (what i read) creates sort of new session without that sourcing i did). 
Do you have something in your mind how i can avoid that error and compile? 

Thank you once again
Ingo

**Comment by TonkomoLLC** [comment] 2021-07-18 14:11
Dear Ingo,

Glad to hear that you have the right video driver for your GPU.  Warning: I have not tried CUDA 11.4 so I have no idea if you will experience new problems associated with the newer version of CUDA. Hopefully you will not. The latest I have personally tried is CUDA 11.1.

With respect to your compilation issue: Perhaps the easiest thing to do, assuming you have root access on your computer, is to enter superuser mode (`su` command) and enter the root password.  Then you can go to `/opt/RapidCFD-dev` and `source etc/bashrc`. Hopefully then `./Allwmake` will work without errors.

Good luck with solving the latest issue. Hope you are up and running soon.

Best regards,

Eric

**Comment by Flowier** [comment] 2021-07-18 15:47
> The latest I have personally tried is CUDA 11.1.

I installed CUDA 11.1 successfully, without errors. i got the notification that it was installed in the installer.
But when i try to compile Rapidcfd with your su which really solved the problem before i get the message that there is no nvcc installed..

When i try "nvcc --version" i get the output that no nvcc is installed
When i then install via apt it automatically installs the version 10.1 which is not compatible with the arch of my gpu

Do you had the problem before?

Best wishes
Ingo

**Comment by TonkomoLLC** [comment] 2021-07-18 16:28
Dear Ingo,

I have a file called setCUDAPath in my /opt/RapidCFD-dev directory. This file contains:

```
export CUDA_HOME=/usr/local/cuda
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64
export PATH=$PATH:$CUDA_HOME/bin
```

Before I compile RapidCFD, I type `source setCUDAPath` from the `/opt/RapidCFD-dev` directory where this `setCUDAPath` file resides.

This should fix your mvcc not found problem.

Good luck with recompilation.

Best regards,

Eric

**Comment by Flowier** [comment] 2021-07-18 17:08
Dear Eric, 

i encounter another problem i did not have before: 

```
root@Flowie:/opt/RapidCFD-dev# source etc/bashrc 
bash: /root/RapidCFD/RapidCFD-dev/bin/foamEtcFile: No such file or directory
bash: /root/RapidCFD/RapidCFD-dev/bin/foamCleanPath: No such file or directory
bash: /root/RapidCFD/RapidCFD-dev/bin/foamCleanPath: No such file or directory
bash: /root/RapidCFD/RapidCFD-dev/bin/foamCleanPath: No such file or directory
bash: /root/RapidCFD/RapidCFD-dev/etc/config/settings.sh: No such file or directory
bash: /root/RapidCFD/RapidCFD-dev/etc/config/aliases.sh: No such file or directory
bash: /root/RapidCFD/RapidCFD-dev/bin/foamCleanPath: No such file or directory
bash: /root/RapidCFD/RapidCFD-dev/bin/foamCleanPath: No such file or directory
bash: /root/RapidCFD/RapidCFD-dev/bin/foamCleanPath: No such file or directory
```
Sorry, that i only get errors :D

**Comment by Flowier** [comment] 2021-07-18 17:09
btw how can i donate to your team? 
I really appreciate your help!

**Comment by TonkomoLLC** [comment] 2021-07-18 17:31
Dear Ingo,

Please try:

- Open a new terminal window
- cd /opt/RapidCFD-dev
- su --> enter root
- `. etc/bashrc`
- If the error still happens, what do you get when you type:

echo $WM_PROJECT_DIR?

If you get something other than `/opt/RapidCFD-dev` then let's try the following.

Edit `/etc/bashrc' as root and look for the text:

```
################################################################################
# USER EDITABLE PART: Changes made here may be lost with the next upgrade
#
# either set $FOAM_INST_DIR before sourcing this file or set
# 'foamInstall' below to where OpenFOAM is installed
#
# Location of the OpenFOAM installation
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
foamInstall=$HOME/$WM_PROJECT
# foamInstall=~/$WM_PROJECT
# foamInstall=/opt/$WM_PROJECT
# foamInstall=/usr/local/$WM_PROJECT
#
# END OF (NORMAL) USER EDITABLE PART
################################################################################
```

Comment (i.e., add a `#`) in front of `foamInstall=$HOME/$WM_PROJECT`, then uncomment (i.e., remove the `#`) in front of `foamInstall=/opt/$WM_PROJECT`. Save your changes in the editor, then once again:

`. etc/bashrc` from `/opt/RapidCFD-dev`

What happens now?

Thanks for your kind words:

```
btw how can i donate to your team?
I really appreciate your help!
```

As you gain experience with RapidCFD, please kindly consider:
- Helping others who post issues on this board
- Posting tutorial cases that may help others learn RapidCFD 
- Contributing to the code base if you find a bug or add features. 

I hope I've given you some good advice with fixing your RapidCFD environment variables. Let's hope it works now.

Cheers,

Eric

**Comment by Flowier** [comment] 2021-07-18 17:38
i tried ". etc/bashrc" after new terminal with "su". Same result
Then i edited the bashrc how you said and here again same result. 

I will help when i have more experience since i know how frustrating that can be :D

**Comment by TonkomoLLC** [comment] 2021-07-18 17:42
Dear Ingo,

If you set foamInstall to `/opt/$WM_PROJECT` in `bashrc`, then after you type `. etc/bashrc`, what is the output of 

```
echo $WM_PROJECT_DIR
```

Thanks for letting me know, so I can help troubleshoot. 

```
I will help when i have more experience since i know how frustrating that can be :D
```

That is perfect!!

Cheers,
Eric

**Comment by TonkomoLLC** [comment] 2021-07-18 17:44
If you get an answer of anything but `/opt/RapidCFD-dev`

try from the command line:

`export FOAM_INST_DIR = /opt/RapidCFD-dev`

then try `. etc/bashrc`

and if the error persists, what is the result of

`echo $WM_PROJECT_DIR`  ?

Thanks,
Eric

**Comment by Flowier** [comment] 2021-07-18 17:54
Ah i see, the output was opt/RapidCFD/RapidCFD-dev so i moved the dir to this path and now the compilation is running! :) 

Thanks you so much Eric! 

I will post here later if the tutorials which didnt work with the previous compilation work with this one.

**Comment by TonkomoLLC** [comment] 2021-07-18 18:08
That's great!  Well done.
Good luck with the next steps.
Cheers,
Eric

**Comment by Flowier** [comment] 2021-07-18 18:17
Thanks. 
Have a nice evening :)

**Comment by Flowier** [comment] 2021-07-18 22:49
Hey Eric,
now the calculation with rhoPimpleFoam (pitzDaily) went trough without errors and i could see the results. Perfect!
Thanks again for your kind help
Best wishes
Ingo

**Comment by TonkomoLLC** [comment] 2021-07-18 22:56
Dear Ingo,

That's great, and you're very welcome!  Glad you are on your way and hope you have achieve some good results.

Cheers,

Eric

**Comment by TonkomoLLC** [comment] 2021-07-18 22:59
Dear Ingo, 

Go ahead and close this issue when you have time. I can't close it for you.  

Thanks,
Eric

**Closed** 2021-07-18 23:17 UTC

**Comment by jiaqiwang969** [comment] 2022-07-29 03:39
> Thanks for your help on that, i looked at the cases and they were solvable.
> 
> Now when i try to calculate the rhoSimpleFoam example from openfoam 2.3.0 i get the following error: ![image](https://user-images.githubusercontent.com/84880991/124957444-621ffd80-e019-11eb-85a2-e0ddbfa028a3.png)
> 
> Do you know what this might be?

Maybe because of the precision of GPU.
